name: BUILD Linux
on:
  push:
    tags:
      - 'v*.**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
      tag_name:
        type: string
        description: 'Tag name'
        required: false
        default: 'tagname'
      tag:
        description: 'Image tag'
        required: true
        default: 'test'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Set Go module
        run: |
          go env -w GO111MODULE=on

      - name: Check out code into current branch
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Make all
        run: |
          make all
        env:
          release_name: ${{ inputs.tag_name != '' && inputs.tag_name || github.ref_name }}
          
      - name: Archive artifacts for oms
        uses: actions/upload-artifact@v1
        with:
          name: oms
          path: ./release/
